### ISSUE TITLE
New Firefox

### ISSUE THREAD

**Issue by gaby2300** [mozilla/reps-tweets#4]
## Tweet should be about
Reps

## Tweet Content
Firefox Quantum

**Comment by MichaelKohler** [comment]
Can you propose a text/link for the tweet itself as well? The paragraph below the "Tweet Content" will be the actual tweet. As it currently is, we would tweet with "Firefox Quantum" which is not really helpful. :)

Thanks for the contribution.

**Comment by MichaelKohler** [comment]
superseded by #5

**Comment by gaby2300** [comment]
I just did!

No problem Michael, I always love to help!
