### ISSUE TITLE
Tweet about Recent Add-ons event in Aligarh, UP, India

### ISSUE THREAD

**Issue by CuriousLearner** [mozilla/reps-tweets#48]
## Tweet should be about
Tweet about Recent Add-ons event in Aligarh, UP, India

## Retweet
https://twitter.com/ErSanyamKhurana/status/969246654426619905

**Comment by MichaelKohler** [comment]
As this event already happened, would it make sense to retweet an event summary? Maybe even a link to a blogpost?

Sorry I couldn't get to this sooner.

**Comment by CuriousLearner** [comment]
@MichaelKohler No issues, I've updated the link to point to the Event Report :)

**Comment by CuriousLearner** [comment]
@MichaelKohler ping :)

**Comment by MichaelKohler** [comment]
Looks like the backend is not running correctly. Will need to check that out, but I don't expect this to be fixed before next week.

**Comment by MichaelKohler** [comment]
The tool is working again, but I'm closing this one as it's quite old now. Happy to have a new issue with a more up to date tweet though.
