### ISSUE TITLE
Mozilla's Community Meeting on Data Protection and Privacy

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/reps-tweets#49]
## Tweet should be about
Mozilla's Community Meeting on Data Protection and Privacy

## Retweet
https://twitter.com/MozillaIN/status/972011958881828864

**Comment by MichaelKohler** [comment]
Looks like the backend is not running correctly. Will need to check that out, but I don't expect this to be fixed before next week.

**Comment by ranjithrajv** [comment]
Can you retweet manually? please.

**Comment by MichaelKohler** [comment]
The tool is working again, but I'm closing this one as it's quite old now. Happy to have a new issue with a more up to date tweet though.
