### ISSUE TITLE
GIDS18

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/reps-tweets#52]
## Retweet
https://twitter.com/RanjithRajV/status/986846623853559808

**Comment by MichaelKohler** [comment]
The section for a Retweet is called "Retweet", not "Tweet Content". With Tweet Content everything below that will be tweeted, in this case that would just be the URL with no text whatsoever. 

Can you change the heading to reflect that this is a Retweet? (and please comment here so I get an email once done) Thanks.

**Comment by ranjithrajv** [comment]
edited, please check.

**Comment by ranjithrajv** [comment]
@michaelkohler any update on this issue?

**Comment by ranjithrajv** [comment]
@MichaelKohler The event is completed, we can close this now.
