### ISSUE TITLE
Evolution of Voice - Future of Interactions

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/reps-tweets#58]
## Tweet should be about
Mozilla Common Voice Event in India

## Retweet
https://twitter.com/RanjithRajV/status/1000267502859894784

**Comment by MichaelKohler** [comment]
@ranjithrajv is it just me or does the meetup link require a login for everyone? If so, I don't think this is very useful to be honest.

**Comment by ranjithrajv** [comment]
requires login for everyone.
