### ISSUE TITLE
WebXR Workshop

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/reps-tweets#62]
## Tweet should be about
Advanced Training Workshop on WebXR at Hyderabad, India

## Retweet
https://twitter.com/SwechaFSMI/status/1018179513929355265

**Comment by couci** [comment]
This is a Swecha and not a Reps event. Therefore the Reps account it's not the right place to tweet about this.

**Comment by ranjithrajv** [comment]
Swecha helped in venue and promotions. It's being organised by MozillaTSAP.
https://discourse.mozilla.org/t/advanced-training-on-webxr-at-hyderabad-india/30137
