### ISSUE TITLE
Onboarding Screening Team 2018-2

### ISSUE THREAD

**Issue by Mte90** [mozilla/reps-tweets#63]
## Tweet should be about
New Onboarding Screening team for 2018-2 

## Tweet Content
New Onboarding Screening team for 2018-2 published on our blog https://blog.mozilla.org/mozillareps/2018/08/08/onboarding-team-for-2nd-half-of-2018/

**Comment by MichaelKohler** [comment]
The blog entry should generate a tweet on its own, so I don't think we want it double. Do we?

**Comment by Mte90** [comment]
You are right we can close it.
